Repository wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-1-7, pull requests merged in 2023-08, with the labels that each got.

#6 feat: #2 라우트 설정 + 기본 페이지 레이아웃 추가
  src/App.tsx
  src/apis/instance.ts
  src/pages/Home.tsx
  src/pages/PageRouter.tsx
  src/pages/Signin.tsx
  src/pages/Signup.tsx
  src/pages/Todo.tsx
Labels: feat

#11 feat: #8 signIn, signup 기능 구현
  src/apis/auth.ts
  src/components/common/Sign/SignForm.styled.tsx
  src/components/common/Sign/SignForm.tsx
  src/components/common/Sign/types.ts
  src/pages/PageRouter.tsx
  src/pages/Signin.tsx
  src/pages/Signup.tsx
Labels: feat

#13 feat: #7 Todo 리스트 구현
  src/apis/todo.ts
  src/components/TodoItem/TodoItem.tsx
  src/components/TodoItem/types.ts
  src/components/TodoList/TodoList.tsx
  src/components/TodoList/types.ts
  src/pages/Todo.tsx
Labels: feat

#12 config: #4 Git hook + Husky 를 활용한 린트, 포매팅 자동화
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
  public/index.html
  src/reportWebVitals.ts
  tsconfig.json
Labels: config

#24 feat : #16 404 페이지 라우터에 추가하기
  src/apis/instance.ts
  src/components/common/Sign/SignForm.tsx
  src/components/common/Sign/types.ts
  src/pages/NotFound.tsx
  src/pages/PageRouter.tsx
  src/pages/Signin.tsx
  src/pages/Signup.tsx
  src/pages/Todo.tsx
Labels: feat

#26 style: #23 컴포넌트 스타일링 - sigin/signup
  src/components/common/Sign/SignForm.styled.tsx
  src/components/common/Sign/SignForm.tsx
Labels: style

#27 style: #18 컴포넌트 스타일링 - Home/Todo 페이지
  src/App.tsx
  src/components/TodoItem/TodoItem.tsx
  src/components/TodoList/TodoList.tsx
  src/pages/Home.tsx
  src/pages/PageLayout.tsx
  src/pages/Todo.tsx
Labels: style

#28 Feat/#25 로그인 후, 투두리스트 페이지에서 투두 데이터 요청 시 401에러
  src/apis/auth.ts
  src/apis/instance.ts
  src/apis/todo.ts
  src/components/common/Sign/SignForm.tsx
  src/components/common/Sign/types.ts
  src/pages/PageRouter.tsx
Labels: bug

#30 config : #10 배포시 필요 파일 작성
  public/_redirects
Labels: config

#33 config: #31 remote에서 병합된 로컬 브랜치 일괄 삭제하는 스크립트 추가
  package.json
Labels: config

#36 bug: #34 /todo -> /signin, /signup 리다이렉팅
  src/pages/PageRouter.tsx
Labels: bug

#38 feat: 홈 페이지 버튼 로그인 여부에 따라 조건부 렌더링
  src/pages/Home.tsx
  src/pages/PageRouter.tsx
Labels: feat

#40 config: #32 favicon, meta data 수정하기
  public/favicon.ico
  public/favicon.png
  public/index.html
  src/assets/MainIcon.svg
  src/pages/Home.tsx
Labels: config

#39 refactor: #37 AuthProvider 를 통한 인증 상태 관리
  src/App.tsx
  src/AuthProvider.tsx
  src/apis/instance.ts
  src/components/common/Sign/SignForm.tsx
  src/components/common/Sign/types.ts
  src/pages/Home.tsx
  src/pages/PageRouter.tsx
  src/pages/Signin.tsx
  src/pages/Signup.tsx
  src/pages/Todo.tsx
Labels: refactor

#44 refactor: SiginForm 이벤트 분기처리 if~else로 변경
  src/components/common/Sign/SignForm.tsx
Labels: refactor

#47 refactor: 페이지 네이밍 리팩토링 컴포넌트+Page
  src/pages/HomePage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/PageRouter.tsx
  src/pages/SigninPage.tsx
  src/pages/SignupPage.tsx
  src/pages/TodoPage.tsx
Labels: refactor

#49 refactor : #42 ThemeProvider를 활용한 색상값 글로벌 테마 등록
  src/App.tsx
  src/components/TodoItem/TodoItem.tsx
  src/components/TodoList/TodoList.tsx
  src/components/common/Sign/SignForm.styled.tsx
  src/pages/HomePage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/PageLayout.tsx
  src/styles/DefaultTheme.ts
  src/styles/colors.ts
  src/styles/common.ts
  src/styles/fontSize.ts
Labels: feat, refactor

#52 refactor: #50 SignForm 리팩토링
  src/components/common/Sign/SignForm.tsx
  src/hooks/useForm.ts
  src/pages/SigninPage.tsx
  src/pages/SignupPage.tsx
Labels: refactor
